### ISSUE TITLE
docker composer will fail

### ISSUE THREAD

**Issue by tboronczyk** [ikknd/docker-study#1]
I read your article at https://hackernoon.com/get-composer-to-run-on-docker-container-a-how-to-guide-y86g36z7 and appreciate the points you make. I too do not like to roll my own container to get PHP and Composer working together. However, your solution is inadequate. Composer executes in its container against its own version of PHP - which will fail any requires for PHP extensions that it doesn't have. For example, pdo-mysql is not installed by default in php:7.4-fpm and should be installed with docker-php-ext-install. This introduces a discrepancy between the containers and composer will fail on require ext-pdo_mysql. I'd be interested to see whether you can solve this.

**Comment by ikknd** [comment]
@tboronczyk Yes, you are right, my example is quite basic, and works well in cases when no specific extensions/configuration is required.
If you need something more complex, I think that a custom composer image can help. I would treat this as a "service" image, where you list only extensions that are needed for it to work, not all extensions that you have in your project.

Here is an example Dockerfile: [https://gist.github.com/ikknd/e4b1701afb589df8483e9c1b0d82b25a](https://gist.github.com/ikknd/e4b1701afb589df8483e9c1b0d82b25a)

You can control php version, and install needed extensions in addition to those needed by composer itself. I have made a very simplified example, in a real project it might be wise to copy [official composer image Dockerfile](https://github.com/composer/docker/blob/6deedc6a8c89b17c9a6ca61a28c8b206513c76f8/1.9/Dockerfile) and adjust it to your needs.

What do you think about this approach?
